name: navigai-api
services:
- name: api
  source_dir: /
  github:
    repo: shashiKundur1/NavigAI-api
    branch: main
  run_command: |
    cd src && python -m uvicorn server:app --host 0.0.0.0 --port $PORT
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  env:
  - key: PYTHONPATH
    value: src
  - key: PORT
    value: "8080"
  - key: CORS_ALLOWED_ORIGINS
    value: http://localhost:3000,http://127.0.0.1:3000,https://navig-ai-client-oegntr6v0-shashidhars-projects-11d35d8d.vercel.app
  - key: GEMINI_API_KEY
    value: AIzaSyCkaLOOtz6kpt0wIXGHBqPooFhV5oea5Cw
    type: SECRET
  - key: THEIR_STACK_API_KEY
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzaGFzaGlkaGFya3VuZHVyMzcxQGdtYWlsLmNvbSIsInBlcm1pc3Npb25zIjoidXNlciIsImNyZWF0ZWRfYXQiOiIyMDI1LTA5LTIxVDE1OjI0OjEzLjIyOTQ3OSswMDowMCJ9.S0pSe1_oLK9gJlepsPph_z5EQWf5WUcJuptm60OlEuA
    type: SECRET
  - key: FIREBASE_PROJECT_ID
    value: navigai
  - key: JWT_SECRET_KEY
    value: f6e4bde336bea5e6e9150792645e16264e67dad33ad1f11bxuzz29cca98840907c0c620c9e3c02474e0861b3cab540ada03ab9231dea0df893f8da
    type: SECRET
  - key: LIVEKIT_URL
    value: wss://navigai-40iru0ui.livekit.cloud
  - key: LIVEKIT_API_KEY
    value: APIKtUNfSqF7i5x
    type: SECRET
  - key: LIVEKIT_API_SECRET
    value: c1WYtOCmwSLfL8ov26cVaYWUtc4xfzj18ZIExtkS5VR
    type: SECRET
  - key: WHISPER_MODEL
    value: small
  - key: SAMPLE_RATE
    value: "16000"
  - key: RECORDING_TIMEOUT
    value: "120"
  - key: SILENCE_THRESHOLD
    value: "3"
  - key: MAX_QUESTIONS
    value: "20"
  - key: LOG_LEVEL
    value: INFO